#!/bin/bash

# Navigate to your project directory
cd /home/pacyheb/flask-material-dashboard

# Pull the latest changes
git --git-dir=/home/pacyheb/flask-material-dashboard/.git --work-tree=/home/pacyheb/flask-material-dashboard checkout -f

# Install any new dependencies (if using pip and requirements.txt)
pip install -r requirements.txt

# Restart your systemd service
sudo systemctl restart discord-bot-dashboard.service
